In [14]:
import gym
import pygame
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

In [15]:
environment_name = "CartPole-v1"

In [16]:
env = gym.make(environment_name,  render_mode="human")

In [4]:
episodes = 50
state = env.reset()
env.action_space.sample()
env.step(1)
print(env.action_space.sample())
print(env.step(1))
for episode in range(1, episodes+1):
    state = env.reset()
    done0 = False
    done1 = False
    score = 0 
    
    while not (done0 or done1):
        env.render()
        action = env.action_space.sample()
        n_state, reward, done0, done1, info = env.step(action)
        score+=reward
        #env.render()
    print('Episode:{} Score:{}'.format(episode, score))
#env.close()

C:\Users\Asus\AppData\Roaming\Python\Python310\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


0
(array([ 0.03238172,  0.35953802, -0.05254175, -0.602642  ], dtype=float32), 1.0, False, False, {})
Episode:1 Score:17.0
Episode:2 Score:15.0
Episode:3 Score:30.0
Episode:4 Score:48.0
Episode:5 Score:33.0
Episode:6 Score:21.0
Episode:7 Score:11.0
Episode:8 Score:22.0
Episode:9 Score:62.0
Episode:10 Score:11.0
Episode:11 Score:18.0
Episode:12 Score:9.0
Episode:13 Score:23.0
Episode:14 Score:19.0
Episode:15 Score:18.0
Episode:16 Score:14.0
Episode:17 Score:35.0
Episode:18 Score:44.0
Episode:19 Score:28.0
Episode:20 Score:38.0
Episode:21 Score:32.0
Episode:22 Score:37.0
Episode:23 Score:15.0
Episode:24 Score:14.0
Episode:25 Score:12.0
Episode:26 Score:28.0
Episode:27 Score:17.0
Episode:28 Score:12.0
Episode:29 Score:38.0
Episode:30 Score:11.0
Episode:31 Score:20.0
Episode:32 Score:20.0
Episode:33 Score:72.0
Episode:34 Score:28.0
Episode:35 Score:14.0
Episode:36 Score:47.0
Episode:37 Score:11.0
Episode:38 Score:21.0
Episode:39 Score:16.0
Episode:40 Score:20.0
Episode:41 Score:41.0
Episod

In [17]:
env.close()

In [18]:
env.action_space.sample()

1

In [7]:
env.observation_space.sample()

array([ 1.4551777e+00,  1.5520964e+38,  1.4288998e-01, -1.5405900e+38],
      dtype=float32)

In [19]:
env = gym.make(environment_name, render_mode="human")
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy', env, verbose = 1)

Using cpu device


C:\Users\Asus\AppData\Roaming\Python\Python310\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


In [20]:
model.learn(total_timesteps=20000)

C:\Users\Asus\AppData\Roaming\Python\Python310\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


-----------------------------
| time/              |      |
|    fps             | 46   |
|    iterations      | 1    |
|    time_elapsed    | 43   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 46          |
|    iterations           | 2           |
|    time_elapsed         | 88          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009238286 |
|    clip_fraction        | 0.135       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.685      |
|    explained_variance   | -0.00403    |
|    learning_rate        | 0.0003      |
|    loss                 | 7.49        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.024      |
|    value_loss           | 51.4        |
-----------------------------------------
----------------------------------

In [16]:
original_env = env.envs[0]

In [13]:
original_env.close()

In [12]:
state

array([[-0.01583749,  0.02976768,  0.02437847, -0.00334277]],
      dtype=float32)

In [26]:
episodes = 10
state = env.reset()

for episode in range(1, episodes + 1):
    state = env.reset()
    done0 = False
    score = 0

    while not done0:
        action, _states = model.predict(state)  # Use 'state' here
        state, reward, done0, info = env.step(action)
        score += reward
        env.render()

    print('Episode:{} Score:{}'.format(episode, score))

Episode:1 Score:[500.]
Episode:2 Score:[500.]
Episode:3 Score:[500.]
Episode:4 Score:[500.]
Episode:5 Score:[500.]
Episode:6 Score:[500.]
Episode:7 Score:[500.]
Episode:8 Score:[500.]
Episode:9 Score:[500.]
Episode:10 Score:[481.]


In [11]:
env.close()